# Generated by Django 4.1.4 on 2022-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_img_alter_blogpost_user_delete_bloguser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="img",
            field=models.ImageField(
                default="https://www.iforium.com/wp-content/uploads/Placeholder-Image-400.png",
                upload_to="pics",
            ),
        ),
    ]
